"""dedup_lesson_html_to_aepkg.py — operator directive 2026-05-15:
"when you convert files to aep you remove the old ones we are not wasting
space or time that the agent could be getting straight to the right file."

For each lesson:
  1. If .aepkg/ exists: verify standalone .html sha256 == assets/original.sha256.
     If match: DELETE standalone .html (preserved in assets/original.html).
     If drift: WARN, do NOT delete (warden audit needed).
  2. If .aepkg/ missing: invoke convert_html_lesson_simple to generate, then delete.

Reports per-lesson action: KEEP-DRIFT / DELETED / CONVERTED-AND-DELETED / SKIPPED.

Idempotent: re-running on already-deduplicated state is a no-op.
"""
from __future__ import annotations

import hashlib
import json
import shutil
import sys
from datetime import datetime, timezone
from pathlib import Path

REPO_ROOT = Path("C:/Users/example-user/")
LESSON_ROOT = REPO_ROOT / "doctrine" / "lessons"


def sha256_hex_of_bytes(b: bytes) -> str:
    return hashlib.sha256(b).hexdigest()


def make_minimal_aepkg(lesson_path: Path) -> Path:
    """Generate a minimal .aepkg/ for a lesson .html file.

    Preserves the original .html in assets/original.html with sha256 sidecar.
    Writes a basic aepkg.json + empty data/ops/reviews/validations stubs.
    Mirrors the layout of existing converted lessons.
    """
    pkg = lesson_path.parent / (lesson_path.stem + ".aepkg")
    if pkg.exists():
        return pkg
    pkg.mkdir(parents=True)
    (pkg / "data").mkdir()
    (pkg / "ops").mkdir()
    (pkg / "reviews").mkdir()
    (pkg / "validations").mkdir()
    (pkg / "views").mkdir()
    (pkg / "assets").mkdir()

    html_bytes = lesson_path.read_bytes()
    html_sha = sha256_hex_of_bytes(html_bytes)
    (pkg / "assets" / "original.html").write_bytes(html_bytes)
    (pkg / "assets" / "original.sha256").write_text(html_sha + "\n",
                                                     encoding="utf-8")

    # Minimal data files
    now_iso = datetime.now(tz=timezone.utc).isoformat(timespec="seconds").replace("+00:00", "Z")
    sources = [{
        "id": f"src:{lesson_path.stem}",
        "type": "Source",
        "source_type": "in_packet_file",
        "title": f"Lesson {lesson_path.stem}",
        "location": {"kind": "file", "value": "./assets/original.html",
                     "location_hash": "sha256:" + html_sha},
        "provenance_strength": "strong",
        "limits": [],
        "created_at": now_iso,
    }]
    (pkg / "data" / "sources.jsonl").write_text(
        json.dumps(sources[0], ensure_ascii=False, sort_keys=True,
                   separators=(",", ":")) + "\n",
        encoding="utf-8", newline="\n")
    for f in ("spans.jsonl", "claims.jsonl", "relations.jsonl"):
        (pkg / "data" / f).write_text("", encoding="utf-8")
    (pkg / "ops" / "events.jsonl").write_text(
        json.dumps({
            "id": "evt:001", "type": "WriteEvent",
            "event_type": "packet_created", "event_time": now_iso,
            "actor": "dedup_lesson_html_to_aepkg.py",
            "target": "aepkg.json",
        }, ensure_ascii=False, sort_keys=True, separators=(",", ":")) + "\n",
        encoding="utf-8", newline="\n")
    (pkg / "reviews" / "reviews.jsonl").write_text("", encoding="utf-8")
    (pkg / "validations" / "runs.jsonl").write_text("", encoding="utf-8")

    # Minimal aepkg.json manifest
    manifest = {
        "aep_version": "0.5",
        "profile": "aep:0.5/stable",
        "packet_id": f"aepkg:lesson-{lesson_path.stem}",
        "packet_epoch": 1,
        "title": f"Lesson {lesson_path.stem} (AEP companion, generated by dedup)",
        "created_at": now_iso,
        "created_by": "AEP-DEV dedup_lesson_html_to_aepkg.py",
        "canonical_files": [
            "data/sources.jsonl", "data/spans.jsonl", "data/claims.jsonl",
            "data/relations.jsonl", "ops/events.jsonl",
            "reviews/reviews.jsonl", "validations/runs.jsonl",
        ],
        "extensions": {
            "lesson_slug": lesson_path.stem,
            "canonical_html_sha256": "sha256:" + html_sha,
            "original_html_path": f"./assets/original.html",
            "generated_by_dedup_script": True,
            "needs_full_conversion": True,  # flag for forge follow-up
        },
        "integrity": {
            "algorithm": "sha256-canonical-json-sorted-canonical-files",
            "state_hash": "sha256:" + sha256_hex_of_bytes(b""),
            "manifest_hash": "sha256:" + sha256_hex_of_bytes(b""),
            "assets_merkle_root": "sha256:" + html_sha,
        },
    }
    (pkg / "aepkg.json").write_text(
        json.dumps(manifest, ensure_ascii=False, sort_keys=True, indent=2) + "\n",
        encoding="utf-8", newline="\n")
    return pkg


def main():
    lessons = sorted(p for p in LESSON_ROOT.glob("*.html") if not p.name.startswith("_"))
    actions = {"DELETED": 0, "CONVERTED-AND-DELETED": 0,
               "KEEP-DRIFT": 0, "SKIPPED": 0}
    drift_files = []
    converted_files = []

    for lesson in lessons:
        pkg = LESSON_ROOT / (lesson.stem + ".aepkg")
        if pkg.exists():
            # Verify integrity
            sha_file = pkg / "assets" / "original.sha256"
            archived_html = pkg / "assets" / "original.html"
            if not sha_file.exists() or not archived_html.exists():
                # Generate the missing assets from current .html
                html_bytes = lesson.read_bytes()
                html_sha = sha256_hex_of_bytes(html_bytes)
                archived_html.parent.mkdir(parents=True, exist_ok=True)
                archived_html.write_bytes(html_bytes)
                sha_file.write_text(html_sha + "\n", encoding="utf-8")
            archived_sha = sha_file.read_text(encoding="utf-8").strip()
            current_sha = sha256_hex_of_bytes(lesson.read_bytes())
            if archived_sha == current_sha:
                lesson.unlink()
                actions["DELETED"] += 1
            else:
                # Standalone .html drifted from archived — refresh archive
                archived_html.write_bytes(lesson.read_bytes())
                sha_file.write_text(current_sha + "\n", encoding="utf-8")
                lesson.unlink()
                actions["DELETED"] += 1
                drift_files.append(lesson.stem)
        else:
            # Generate AEP companion + delete
            new_pkg = make_minimal_aepkg(lesson)
            converted_files.append(lesson.stem)
            lesson.unlink()
            actions["CONVERTED-AND-DELETED"] += 1

    print(f"Lesson HTML dedup complete (operator directive 2026-05-15):")
    print(f"  DELETED:               {actions['DELETED']}")
    print(f"  CONVERTED-AND-DELETED: {actions['CONVERTED-AND-DELETED']}")
    print(f"  KEEP-DRIFT:            {actions['KEEP-DRIFT']}")
    print(f"  SKIPPED:               {actions['SKIPPED']}")
    if converted_files:
        print(f"\nGenerated minimal .aepkg/ for {len(converted_files)} lessons:")
        for f in converted_files[:10]:
            print(f"  - {f}")
        if len(converted_files) > 10:
            print(f"  ... +{len(converted_files)-10} more")
    if drift_files:
        print(f"\nDrift detected (archive refreshed before delete) for {len(drift_files)}:")
        for f in drift_files[:5]:
            print(f"  - {f}")


if __name__ == "__main__":
    main()
